seed: 42
paths:
  data: ./data
  staged: ./data/staged
  features: ./data/features
  models: ./data/models
  reports: ./data/reports
slo:
  ingest_minutes_per_season: 5
  features_minutes: 2
  baseline_train_minutes_per_season: 3
  team_strength_minutes: 2
  sim_full_slate_seconds: 60
ingest:
  seasons: [2023]
sim:
  sims_per_game: 512  # 256–1024 acceptable
  ci_width_target_margin: 0.3
decision:
  k_top: 5
  prob_threshold: 0.62
  kelly_fraction: 0.25
  max_stake_pct_per_bet: 0.02
  max_stake_pct_per_game: 0.03
  max_weekly_exposure_pct: 0.15
uer:
  recency_half_life_weeks: 6
  ridge_lambda: 10.0
  min_snaps_threshold: 50
strategy:
  recency_half_life_weeks: 6
  min_samples_per_coach: 200
  aggressiveness_targets: ["PROE", "4th_go", "2pt", "tempo"]
context:
  update_latency_budget_s: 0.5
  partial_sim_max_ms: 200
health:
  recency_half_life_weeks: 8
  min_events: 50
  frailty: true
roster:
  min_snaps_for_starter: 200
  fallback_by_position:
    WR: ["WR4", "TE2", "RB3"]
    RB: ["RB2", "WR4", "TE2"]
    CB: ["CB4", "S3"]
  qb_replacement_penalty: 0.7
impact:
  samples_per_player: 200
  ci_level: 0.90
  max_games_per_batch: 8
  seed: 13
meta:
  seed: 14
  kfold: 5
  stacker: "logit"
calibrate:
  method: "isotonic"
  bins: 10
conformal:
  coverage: 0.90
  margin_quantiles: [0.05, 0.95]
  total_quantiles: [0.05, 0.95]
