seed: 42
paths:
  data: ./data
  staged: ./data/staged
  features: ./data/features
  models: ./data/models
  reports: ./data/reports
slo:
  ingest_minutes_per_season: 5
  features_minutes: 2
  baseline_train_minutes_per_season: 3
  team_strength_minutes: 2
  sim_full_slate_seconds: 60
sim:
  sims_per_game: 512  # 256–1024 acceptable
  ci_width_target_margin: 0.3
