name: a22a-ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: |
          if [ -f pyproject.toml ]; then pip install .; else pip install -r requirements.txt; fi
      - name: Doctor
        run: python -m a22a.tools.doctor --ci
      - name: Unit tests
        run: python -m pytest -q
