name: Scheduled Pipelines

# Weekly automation for Phase 20. Uses offline-friendly fallbacks unless
# the optional secrets below are populated for live integrations.
# Pipeline order: ingest → features → train → sim → meta → portfolio → market → clv → report_batch → monitor

on:
  schedule:
    - cron: '0 9 * * MON'
  workflow_dispatch:

jobs:
  weekly-pipeline:
    name: Weekly offline pipeline
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: '1'
      PYTHONHASHSEED: '1'
      TZ: 'UTC'
      A22A_LIVE_MODE: '0'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install project in editable mode
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run make doctor
        run: make doctor
      - name: Run scheduled pipeline
        run: bash scripts/run_pipeline.sh
        env:
          A22A_API_TOKEN: ${{ secrets.A22A_API_TOKEN }}
          A22A_MARKET_KEY: ${{ secrets.A22A_MARKET_KEY }}
          STREAMLIT_SERVER_HEADLESS: 'true'
      - name: Upload reports and artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scheduled-pipeline-artifacts
          if-no-files-found: warn
          retention-days: 14
          path: |
            reports
            artifacts/monitor/health_*.json
            artifacts/backtest/summary_*.json
            artifacts/store/a22a_metrics.duckdb
