name: Scheduled Pipelines

# Weekly automation for Phase 20. Uses offline-friendly fallbacks unless
# the optional secrets below are populated for live integrations.
# Pipeline order: ingest → features → train → sim → meta → portfolio → market → clv → report_batch → monitor

on:
  schedule:
    - cron: '0 9 * * MON'
  workflow_dispatch:

jobs:
  weekly-pipeline:
    name: Weekly offline pipeline
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: '1'
      A22A_LIVE_MODE: '0'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run scheduled pipeline
        run: |
          bash scripts/run_pipeline.sh
        env:
          A22A_API_TOKEN: ${{ secrets.A22A_API_TOKEN }}
          A22A_MARKET_KEY: ${{ secrets.A22A_MARKET_KEY }}
          STREAMLIT_SERVER_HEADLESS: 'true'
